<a href="https://colab.research.google.com/github/gwon0919/my-record/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
# 수식을 통해 결과를 얻을 수 있으나 외부 모듈을 사용하면 수식없이 빠르게 결과를 얻을 수 있다.
# 개념을 이해하고 함수나 메소드를 활용하자.
# 평균, 분산, 표준 편차 구하기

grades = [1,3,-2,4]


grades = [1,3,-2,4]

def grades_sum(grades):
  tot = 0
  for g in grades:
    tot += g
  return tot

def grades_avg(grades):
  tot = grades_sum(grades)
  ave = tot / len(grades)
  return ave

def grades_variance(grades):
  ave = grades_avg(grades)
  vari = 0
  for su in grades:
    vari += (su - ave) ** 2
  return vari / len(grades)  # 모집단으로 계산
  #return vari / (len(grades) - 1)  # 표본집단으로 계산

def grades_std(grades):
  return grades_variance(grades) ** 0.5

In [ ]:
print('합은', grades_sum(grades))
print('평균은', grades_avg(grades))
print('분산은', grades_variance(grades))
print('표준편차는', grades_std(grades))

# NumPy를 사용하여 성적 계산
import numpy as np
print('합은', np.sum(grades))  # np.abssum 대신 np.sum 사용
print('평균은', np.mean(grades), ' ', np.average(grades))  # np.mean 또는 np.average 사용
print('분산은', np.var(grades))
print('표준편차는', np.std(grades))

In [ ]:
# numpy 모듈(라이브러리)
# 다차원 배열자료구조인 NDArrary, 선형대수 계산. 벡터 연산. 미적분 등을 지원
import numpy as np
ss = ['tom', 'oscar', 'john', 12, 12.3]
print(ss, type(ss))
ss2 = np.array(ss)      # list를 ndarray로 변환. 같은 type으로 요소값 구성. 상위 type으로 변환 int -> float -> complex -> str
print(ss2, type(ss2))

In [ ]:
# 메모리 비교 (list vs ndarrary)
# list
li = list(range(1,10))
print(li)
print(id(li[0]),id(li[1]))
print(li*10)
for i in li:
  print(i * 10, end=' ')

print('\n')
# ndarray
num_arr = np.array(li)
print(num_arr)
print(id(num_arr[0]), id(num_arr[1]))
print(num_arr * 10)


In [ ]:
a = np.array([1,2,3])   # 1차원 배열
print(a, type(a), a.dtype, a.shape, a.size)
print(a[0], a[2])
a[0]= 7
print(a)

In [42]:
b = np.array([[1,2,3], [4,5,6]], dtype='float32')   # 2차원 배열
print(b, type(b), b.dtype, b.shape, b.size)
print(b[0,0],b[0,2])  # 1 3
print(b[[0]])   # [[1 2 3]]


[[1. 2. 3.]
 [4. 5. 6.]] <class 'numpy.ndarray'> float32 (2, 3) 6
1.0 3.0
[[1. 2. 3.]]


In [48]:
c = np.zeros((2,2))
print(c)

d = np.ones((2,2))
print(d)

e = np.full((2,2), 7)
print(e)

f = np.eye(3)
print(f)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [60]:
np.random.seed(0)
print(np.random.rand(5))  # 균등분포를 따르는 난수
print(np.random.randn(5)) # 정규분포를 따르는 난수

print(np.random.randint(10, size = 6))
print(np.random.randint(10, size = (3,4,5)))


[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[-0.84272405  1.96992445  1.26611853 -0.50587654  2.54520078]
[5 9 8 9 4 3]
[[[0 3 5 0 2]
  [3 8 1 3 3]
  [3 7 0 1 9]
  [9 0 4 7 3]]

 [[2 7 2 0 0]
  [4 5 5 6 8]
  [4 1 4 9 8]
  [1 1 7 9 9]]

 [[3 6 7 2 0]
  [3 5 9 4 4]
  [6 4 4 3 4]
  [4 8 4 3 7]]]


In [67]:
# 인덱싱, 슬라이싱
a = np.array([1,2,3,4,5])
print(a)
print(a[0])
print(a[1:3])
print(a[1:5:2])

print()
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)
print(b[:])
print(b[0,0])
print(b[[0]])
print(b[[0]], b[0],b[0][0]) # [[1 2 3 4]] [1 2 3 4] 1
print(b[1:, 0:2])

print()
c = b[:2, 1:3]
print(c)
print(c[0,0])
c[0,0] = 99
print(c)
print(b)

[1 2 3 4 5]
1
[2 3]
[2 4]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[[1 2 3 4]]
[[1 2 3 4]] [1 2 3 4] 1
[[ 5  6]
 [ 9 10]]

[[2 3]
 [6 7]]
2
[[99  3]
 [ 6  7]]
[[ 1 99  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
